# Import library

In [2]:
import numpy as np

# Question 1

In [5]:
a = np.array([0,1,2,3,4,5,6])
my_liste = []
for i in a:
    my_liste.append(a[i])
print("Le tableau est",a)
print("La liste est",my_liste)

Le tableau est [0 1 2 3 4 5 6]
La liste est [0, 1, 2, 3, 4, 5, 6]


# Question 2

In [17]:
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
somme = 0
for i in range(a.shape[0]):
    somme += a[i][i]
print(a)
print("La somme de l'élément diagonal est",somme)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
La somme de l'élément diagonal est 30


# Question 3

In [21]:
a = np.array([[1,2],[3,5]])
x = 2
print(a[a>x])

[3 5]


# Question 4

In [22]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.add(A,B)
print(C)

[[ 6  8]
 [10 12]]
